language: java
script:
- ./gradlew build
- bash checkdir.sh
notifications:
  slack: ecse321-group18:tJheLEmh0qxP7QBcS8dSegUe
jdk:
  - oraclejdk9
deploy:
  provider: heroku
  api_key: 0d2d6a3a-a07c-4f2b-b209-450f71f35ad6 
  app: cooperatorapp-backend-18
